---
title: "Music and Ballet"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'ballet.html'))})
output: 
  html_document:
    css: css/balletCSSBackground.css
    theme: readable
---

Below is a dataset of 13 popular ballets. 

```{r, echo=F, message=F}
# PACKAGES
library(dplyr)
library(lubridate)
library(kableExtra) 
library(ggplot2)
library(RColorBrewer)
library(plotly)
```

```{r, echo = F}
# DATA 
# 13 Popular ballets (in counting)
# data from wiki searches 
Ballet <- c("Swan Lake", 
            "The Nutcracker", 
            "Giselle", 
            "Romeo and Juliet",  
            "Don Quixote", 
            "Cinderella ", 
            "La Bayadere", 
            "Coppelia", 
            "The Sleeping Beauty ", 
            "La Sylphide ", 
            "Spartacus", 
            "Alice's Adventures in Wonder Land",
            "Firebird")
Composer <- c("Pyotr Ilyich Tchaikovsky", 
              "Pyotr Ilyich Tchaikovsky",
              "Adolph Adam", 
              "Sergei Prokofiev",
              "Ludwig Minkus",
              "Sergei Prokofiev",
              "Ludwig Minkus",
              "Leo Delibes",
              "Pyotr Ilyich Tchaikovsky",
              "Filippo Talioni",
              "Leonid Yakobson",
              "Joby Talbo",
              "Igor Stravinsky ")
choreographer_1 <- c("Julius Reisinger",
                     "Marius Petipa", 
                     "Jean Coralli",
                     "Ivo Vana-Psota",
                     "Marius Petipa", 
                     "Rosstislav Zakharov",
                     "Marius Petipa",
                     "Arthur Saint-Leon",
                     "Marius Petipa",
                     "Jean-Madeline Schnitzhoeffer",
                     "Aram Khachaturian",
                     "Christopoher Wheeldon",
                     "Michel Fokine")
choreographer_2 <- c("",
                     "Lev Ivanov",
                     "Jules Perrot",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "",
                     "")
Acts <- c(4, 2, 2, 4, 3, 3, 4, 2, 3, 2, 3, 3, 1)
month_premiered <- c( 3, 12, 6, 12, 12, 11, 2, 5, 1, 3, 12, 2, 6)
day_premiered <- c( 4, 18, 28, 30, 26, 21, 11, 25, 5, 12, 27, 28, 9)
year_premiered <- c(1877, 1892, 1841, 1938, 1869, 1945, 1877, 1870, 1890, 1832, 1956, 2011, 1910)
### Coming Soon
Links <- c("https://www.youtube.com/watch?v=LbUatYSm8ME", 
            "The Nutcracker", 
            "Giselle", 
            "Romeo and Juliet",  
            "Don Quixote", 
            "Cinderella ", 
            "https://www.youtube.com/watch?v=zTR4Oco_0Bc", 
            "Coppelia", 
            "The Sleeping Beauty ", 
            "https://www.youtube.com/watch?v=R_RFxSLar2A", 
            "https://www.youtube.com/watch?v=Fha6rYtaLMk", 
            "https://www.youtube.com/watch?v=c2wWq25p5Sk",
            "https://www.youtube.com/watch?v=Yo9L9H--t3k")

```

```{r, echo=F}
# CREATE DATAFRAME AND WRANGLE DATA 
ballet.df <- data.frame(Ballet, 
                        Composer, 
                        "First Choreographer" = choreographer_1, 
                        "Second Choreographer" = choreographer_2, 
                        Acts, 
                        month_premiered, 
                        day_premiered, 
                        year_premiered)
ballet.df <- ballet.df %>% 
  select(Ballet, Acts, Composer, First.Choreographer) %>%
  mutate(Date.Premiered = make_date(year_premiered, month_premiered, day_premiered)) %>%
  arrange(Ballet) 
```

```{r, echo=F}
# Create Color Pallete 
nb.cols <- 13
mycolors <- colorRampPalette(brewer.pal(7, "Pastel2"))(nb.cols)
# TABLE 
kable(ballet.df) %>%
  column_spec(1:5, background = mycolors) %>%
  row_spec(0:13, align = "c")
```


```{r, echo = F}
# date premiered 
plot <- ballet.df %>% 
  ggplot(aes(x= Date.Premiered, y = Ballet, color = factor(Acts))) +
  geom_point() +
  labs(x = "Date Premiered", y = "Ballet", color = "Number of Acts") +
  ggtitle("Ballets by Date Premiered")
ggplotly(plot)

```

